# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhengxuan Luan
description: >- # this means to ignore newlines until "baseurl:"
  Zhengxuan Luan's personal page
baseurl: # the subpath of the site
url: "https://zhengxuan-luan.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-picture.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      value: https://zhengxuan-luan.github.io
    #   slug: /
    - name: CV
      value: https://zhengxuan-luan.github.io/file/cv.pdf
    # - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: luanzhengxun7@xjtu.stu.edu.cn
      link: mailto:luanzhengxuan7@xjtu.stu.edu.cn
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  # follow:
  #   - name: Twitter
  #     link: http://twitter.com/YourTwitterUsername
  #     username: "@YourTwitterUsername"
  #   - name: Facebook
  #     link: http://facebook.com/YourFacebookUsername
  #   - name: LinkedIn
  #     link: http://linkedin.com/in/YourLinkedInUsername
  #   - name: GitHub
  #     link: http://github.com/YourGitHubUsername
  #   - name: Dribbble
  #     link: https://dribbble.com/YourDribbbleUsername
  #   - name: RSS
  #     link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 10
